name: CI

on:
  push:
    branches:
      - "master"
    tags: "*"
  pull_request:

# Cancel previous runs of this workflow for the same pull request
# `github.head_ref`: https://stackoverflow.com/a/67939898/1404966
# `github.run_id`: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format-check-prettier:
    name: "Check Formatting (Prettier)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Verify that Prettier does not find any code style issues."
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: . --check
